function Section2() {
  
  return (
    <div className="Section2">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc lobortis mattis aliquam faucibus purus in massa. Tellus id interdum velit laoreet id donec ultrices. Eu ultrices vitae auctor eu augue ut. Est sit amet facilisis magna etiam tempor orci eu. Condimentum mattis pellentesque id nibh tortor. Amet tellus cras adipiscing enim eu turpis egestas. Nulla facilisi cras fermentum odio eu. Vel eros donec ac odio tempor orci dapibus ultrices in. Netus et malesuada fames ac. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Suscipit adipiscing bibendum est ultricies integer quis auctor. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Nibh tellus molestie nunc non blandit massa enim nec dui. Ultricies mi eget mauris pharetra.
      <br/>
      Velit ut tortor pretium viverra suspendisse potenti. Quis hendrerit dolor magna eget est lorem ipsum. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Placerat in egestas erat imperdiet sed. Facilisis mauris sit amet massa vitae. Nibh tellus molestie nunc non blandit massa enim. Iaculis urna id volutpat lacus. Commodo sed egestas egestas fringilla. Lectus urna duis convallis convallis tellus id interdum velit laoreet. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Odio euismod lacinia at quis risus sed. At erat pellentesque adipiscing commodo elit at imperdiet. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Et leo duis ut diam quam nulla porttitor. Ornare quam viverra orci sagittis eu volutpat odio. Sit amet mauris commodo quis imperdiet massa tincidunt nunc. Sit amet facilisis magna etiam tempor. Tortor id aliquet lectus proin nibh nisl.
      <br/>
      Egestas congue quisque egestas diam. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Turpis nunc eget lorem dolor sed viverra. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Interdum varius sit amet mattis vulputate enim nulla. Quam viverra orci sagittis eu. Donec enim diam vulputate ut pharetra. Maecenas volutpat blandit aliquam etiam. Diam volutpat commodo sed egestas. Sagittis eu volutpat odio facilisis mauris sit amet massa. Rutrum quisque non tellus orci ac auctor augue. Posuere sollicitudin aliquam ultrices sagittis. Nisi quis eleifend quam adipiscing vitae proin sagittis.
      <br/>
      Netus et malesuada fames ac turpis egestas maecenas pharetra. Fermentum iaculis eu non diam. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Sem viverra aliquet eget sit amet tellus cras. Cras fermentum odio eu feugiat pretium nibh. Maecenas volutpat blandit aliquam etiam erat. Sed euismod nisi porta lorem mollis aliquam. Lorem ipsum dolor sit amet. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Vitae tempus quam pellentesque nec nam. Eu consequat ac felis donec et odio pellentesque diam volutpat. Velit ut tortor pretium viverra suspendisse potenti nullam. Erat velit scelerisque in dictum non consectetur. Eros donec ac odio tempor. Adipiscing commodo elit at imperdiet dui. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Et ultrices neque ornare aenean euismod. Diam maecenas sed enim ut sem viverra.
      <br/>
      Ac turpis egestas sed tempus urna et pharetra. Blandit volutpat maecenas volutpat blandit aliquam. Habitant morbi tristique senectus et netus et malesuada fames ac. Tellus orci ac auctor augue mauris augue. Leo vel fringilla est ullamcorper eget nulla facilisi. Purus non enim praesent elementum. Et ultrices neque ornare aenean euismod elementum. In hac habitasse platea dictumst. Aliquam faucibus purus in massa tempor nec. Viverra ipsum nunc aliquet bibendum enim. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. 
    </div>
  );
}

export default Section2;
